# Generated by Django 2.2.4 on 2019-08-07 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='address',
            new_name='phonenum',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='room',
            new_name='room_name',
        ),
        migrations.RemoveField(
            model_name='building',
            name='tele_num',
        ),
    ]
