# Generated by Django 2.2.4 on 2019-08-07 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20190807_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='phonenum',
        ),
    ]
