# Generated by Django 2.2.4 on 2019-08-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_remove_building_phonenum'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='address',
            field=models.TextField(default='address'),
        ),
        migrations.AddField(
            model_name='building',
            name='room_img',
            field=models.ImageField(default='image', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='building',
            name='tele_num',
            field=models.TextField(default='number'),
        ),
        migrations.AlterField(
            model_name='building',
            name='room_name',
            field=models.TextField(default='name'),
        ),
    ]
