# Generated by Django 2.2 on 2019-08-09 10:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 10, 46, 13, 946311, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='building',
            name='room_img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
