# Generated by Django 2.2 on 2019-08-09 11:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20190809_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 11, 53, 11, 430483, tzinfo=utc), verbose_name='date published'),
        ),
    ]
