# Generated by Django 2.2 on 2019-08-09 20:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20190809_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 20, 12, 49, 792480, tzinfo=utc), verbose_name='date published'),
        ),
    ]
